### ISSUE TITLE
As an author I want to make posts

### ISSUE THREAD

**Issue by saemorris** [CMPUT404WIN17BUMBLEBEE/CMPUT404-project-socialdistribution#1]

**Comment by shadownater** [comment]
So far (as of commit 3dbe6ae29ba23485fb05eee138df419e6e0fe809), a person (not specifically an author) can make posts. They're free-floating for now. At /posts/, you can see a clickable list of posts made from the past two days.

**Comment by shadownater** [comment]
As of commit 337359c0908fc1b26026b9c5273badf3c05740b6 in branch posts, this is possible.
